### PR TITLE
Port to Python 3

### PR DESCRIPTION
**Pull request by pradal**
The aim of this PR is to finally port Phenomenal to Python 3.7.

### CODE REVIEW

**Comment by artzet-s** [comment]
So, all the notebook and all the test pass on my computer (ubuntu 16.04, linux 64) with conda -c conda-forge installation (restriction to networkx=2.3).


Major code modification : 

============================================================================

```
    except Exception, e:
        assert e.message == <something>
```
to :
```
    except Exception as e:
        assert str(e) == <something>
```

============================================================================

```
map(tuple, elements)
```
to
```
list(map(tuple, elements))
```

============================================================================

**Comment by artzet-s** [comment]
Test seems to not be called during CI/CD ?

**Comment by pradal** [comment]
Yes. Right. I have extended travis. I will do the same for AppVeyor once

**Comment by artzet-s** [comment]
- I Don't agree at all with visible appveyor.yml and travis.yml files, is a bad thing.
- Tests are still not called, i'll try a another method 
- Python 2.7 support **must** be stopped, don't need to try CI with that (plus it doesn't work), the last version in python 2.7 of openalea.phenomenal will be the 1.6.1. This version (in python 2.7) is suffisant to assure that all the analysis pipeline work.

**Comment by artzet-s** [comment]
Ok, it seems that the build pass everywhere except with PR mode on win32 (weird ...) . Tests are still not called with that methods. So I put in the meta.yml with pytest. On my machine the conda build work well and call with pytest the different test (See next commit)

**Comment by artzet-s** [comment]
To be more precise with python 2.7 openalea.phenomenal version. I think that we need just to keep the version 1.6.* installable.

**Comment by artzet-s** [comment]
Tests are now well called, and linux x64 pass but no osx (seems that libpng is the cause).

**Comment by pradal** [comment]
I find that there are problems in the order of the channels.
In our case, everything works if coda-forge is ... the first.

**Comment by artzet-s** [comment]
https://github.com/openalea/travis-ci/blob/master/config.sh ? here

**Comment by pradal** [comment]
No. I think that the build is OK. But the test/install is not.
I will check on the results of the CI

**Comment by artzet-s** [comment]
I don't understand why build (on appveyor) pass in branch mode but not in PR .... (for x86). Need to look why monday.

**Comment by pradal** [comment]
On Travis, the test fail only on OSX due to cv2.
I will look at Windows.

**Comment by pradal** [comment]
On Windows, it fails due to an error in the SAT solver of Conda.
Just sleep and it wll work later on.

**Comment by artzet-s** [comment]
https://github.com/conda-forge/opencv-feedstock/issues/127

Yes the fail on OSX seems to be link with opencv, issue is in wip

**Pull request merged**
